### ISSUE TITLE
New Meetup Topics

### ISSUE THREAD

**Issue by brewcore** [TechLancaster/community#1]
A place to start aggregating ideas for new meetup topics.  These don't have to be new meetups, they can just be topics for an existing meetup like TechLancaster.

**Comment by brewcore** [comment]
Agile processes.

**Comment by tomswartz07** [comment]
Multirotors/Quadcopters/Drones and the math/science behind them?

**Comment by brewcore** [comment]
Non-technical but related geeky stuff: anime, sci-fi, comics, etc.

**Comment by brewcore** [comment]
Cleaning up old issues
